# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'kitura-safe-ios-client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kitura-safe-ios-client
  pod 'Starscream', '~> 3.1.0'
end
