# Uncomment the next line to define a global platform for your project
platform :macos, '10.14'

target 'kitura-safe-lab-dashboard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for kitura-safe-lab-dashboard
  pod 'Starscream', '~> 3.0.2'
end
